# Generated by Django 3.1.5 on 2021-01-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subiinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=8)),
                ('district', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=20)),
                ('cel', models.CharField(max_length=20)),
                ('visit_times', models.CharField(max_length=50)),
                ('visit_lastdate', models.DateField()),
            ],
        ),
    ]
